// Bundles Functions/data/*.json into Functions/data.js (window.FUNCTIONS = [...])
// so index.html can be opened directly (file://) without a server.
const fs = require("fs");
const path = require("path");

const dataDir = path.join(__dirname, "data");
const outFile = path.join(__dirname, "data.js");

const files = fs.readdirSync(dataDir).filter((f) => f.endsWith(".json"));
const functions = files.map((f) => {
  const raw = fs.readFileSync(path.join(dataDir, f), "utf8");
  try {
    return JSON.parse(raw);
  } catch (e) {
    throw new Error(`Invalid JSON in ${f}: ${e.message}`);
  }
});

functions.sort((a, b) => a.name.localeCompare(b.name));

const banner = "// Auto-generated by build.js — do not edit by hand.\n";
fs.writeFileSync(
  outFile,
  banner + "window.FUNCTIONS = " + JSON.stringify(functions, null, 2) + ";\n"
);

console.log(`Bundled ${functions.length} function(s) into ${path.relative(process.cwd(), outFile)}`);
